language: elixir
elixir:
  - 1.4.5
  - 1.5.3
  - 1.6.1
otp_release:
  - 19.3
  - 20.2
script:
  - mix test
  - cd interop && mix deps.get && mix run script/run.exs
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
